### ISSUE TITLE
Occasional iced_x86 error

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#1171]
```
thread '<unnamed>' panicked at /ci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced-x86-1.21.0/src/decoder.rs:1421:25:
09:48:11    |attempt to subtract with overflow
09:48:11    |note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
09:48:11    |thread '<unnamed>' panicked at ykrt/src/mt.rs:649:46:
09:48:11    ...
```

Upstream reckons we have corrupted the stack -- sounds like something we could do:
https://github.com/icedland/iced/issues/383

**Comment by ltratt** [comment]
Just to confirm: this does still happen, though infrequently.

**Comment by vext01** [comment]
I've not seen it for a while.
