### ISSUE TITLE
`TransitionGuardFailure::NoAction` needs to be implemented in `mt.rs`.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#1341]
When running the awfy benchmarks I just saw:
```
Executing run:Queens (YkLua, awfy, 1000) default None None None
    cmd: /ci/yklua/src/yklua  harness.lua Queens 1  1000
    cwd: /ci/awfy/Lua
    Run failed. Return code: 134
    Output:

        Starting Queens benchmark ...
        thread '<unnamed>' panicked at ykrt/src/mt.rs:543:49:
        not yet implemented
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
        panic in a function that cannot unwind
        stack backtrace:
           0:     0x7f73aa4e9b1d - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h4f9f0817e56b2800
           1:     0x7f73aa50d30b - core::fmt::write::h8555e7462120c82b
           2:     0x7f73aa4e74d3 - std::io::Write::write_fmt::h88e8d425fe2e683c
           3:     0x7f73aa4eacd2 - std::panicking::default_hook::{{closure}}::h594c38f77836119c
           4:     0x7f73aa4ea93e - std::panicking::default_hook::hccd160a0a5d55adf
           5:     0x7f73aa4eb53f - std::panicking::rust_panic_with_hook::he59475a651e09a8f
           6:     0x7f73aa4eb283 - std::panicking::begin_panic_handler::{{closure}}::h30563074d268c1c8
           7:     0x7f73aa4ea009 - std::sys::backtrace::__rust_end_short_backtrace::h01b637b4bb4d4dcd
           8:     0x7f73aa4eaf44 - rust_begin_unwind
           9:     0x7f73aa50afe5 - core::panicking::panic_nounwind_fmt::hc5acbe128ef147c8
          10:     0x7f73aa50b072 - core::panicking::panic_nounwind::h158b6fdbce3c8b85
          11:     0x7f73aa50b1b6 - core::panicking::panic_cannot_unwind::h9de88922e59ab0fe
          12:     0x7f73aa477ec0 - __yk_deopt
          13:     0x7f73aa3c9626 - <unknown>
        thread caused non-unwinding panic. aborting.
        Aborted (core dumped)
```

https://github.com/ykjit/yk/blob/081be0f6da39f024c365bf7a7fa70e9f89788be9/ykrt/src/mt.rs#L543

Something to do with side tracing.

**Comment by ltratt** [comment]
Can you provide a stand-alone command line to execute this, please? I can then look into it.

**Comment by vext01** [comment]
I found this in as-yet-unmerged work in yk-benchmarks.

I've made a branch that you can run `tryci` on:
https://github.com/vext01/yk-benchmarks/tree/repro-1341

The CI script runs the smoke test 100 times and that's usually enough to shake it out after a while.

**Comment by ltratt** [comment]
Update after online discussions: 3f0f15dc5a27e698d86ba065ec5236a0b2df4505 says it "disables side-traces", but it doesn't. Rather it increases it to a not-very-high number (500,000) so it's easy to see side tracing happen and then exploding. A quick hack is to increase that threshold to `u32::MAX`, though even that doesn't actually *disable* side-traces, though it does make them less likely to happen.

**Comment by ltratt** [comment]
Fixed in https://github.com/ykjit/yk/pull/1364/.
