### ISSUE TITLE
Not all promotions are always consumed

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#1455]
In https://github.com/ykjit/yk/pull/1454 I added an `assert` to check that all promotions are consumed by trace_builder: but they aren't! `gc.lua` fails:

```
16:49:40 .thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/trace_builder.rs:1299:9:
16:49:40 assertion `left == right` failed
16:49:40 left: 48
16:49:40 right: 60
16:49:40 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
16:49:40 thread '<unnamed>' panicked at ykrt/src/mt.rs:337:46:
```

i.e. after building the trace, 12 bytes of promotion data were unconsumed.

**Comment by ltratt** [comment]
Fixed in #1454.
