### ISSUE TITLE
Non-serialised compilation and an extra trace?

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#1458]
yklua on `permute.lua` gives different behaviour with serialised/non-serialised compilation. Most obviously it crashes on the latter, after executing vastly more traces:

```
$ YK_LOG=4 YKD_SERIALISE_COMPILATION=1 src/lua permute.lua 2>&1 | wc -l
67
$ YK_LOG=4 src/lua permute.lua 2>&1 | wc -l
8232
```

That second number is non-deterministic. The Rust backtrace we get for the errors is in lsregalloc:

```
thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/codegen/x64/lsregalloc.rs:662:22:                                                                                     [125/1809]
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/panicking.rs:148:5
   3: core::option::unwrap_failed
             at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/option.rs:2008:5
   4: core::option::Option<T>::unwrap
             at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/option.rs:971:21
   5: ykrt::compile::jitc_yk::codegen::x64::lsregalloc::LSRegAlloc::force_gp_unspill
             at /vol/extra/ltratt/yk/ykrt/src/compile/jitc_yk/codegen/x64/lsregalloc.rs:662:22
   6: ykrt::compile::jitc_yk::codegen::x64::lsregalloc::LSRegAlloc::put_input_in_reg
             at /vol/extra/ltratt/yk/ykrt/src/compile/jitc_yk/codegen/x64/lsregalloc.rs:553:17
   7: ykrt::compile::jitc_yk::codegen::x64::lsregalloc::LSRegAlloc::assign_gp_regs
             at /vol/extra/ltratt/yk/ykrt/src/compile/jitc_yk/codegen/x64/lsregalloc.rs:481:25
   8: ykrt::compile::jitc_yk::codegen::x64::Assemble::emit_call
             at /vol/extra/ltratt/yk/ykrt/src/compile/jitc_yk/codegen/x64/mod.rs:1531:21
   9: ykrt::compile::jitc_yk::codegen::x64::Assemble::cg_call
             at /vol/extra/ltratt/yk/ykrt/src/compile/jitc_yk/codegen/x64/mod.rs:1426:9
  10: ykrt::compile::jitc_yk::codegen::x64::Assemble::cg_insts
             at /vol/extra/ltratt/yk/ykrt/src/compile/jitc_yk/codegen/x64/mod.rs:468:42
  11: ykrt::compile::jitc_yk::codegen::x64::Assemble::codegen
             at /vol/extra/ltratt/yk/ykrt/src/compile/jitc_yk/codegen/x64/mod.rs:286:9
  12: <ykrt::compile::jitc_yk::codegen::x64::X64CodeGen as ykrt::compile::jitc_yk::codegen::CodeGen>::codegen
             at /vol/extra/ltratt/yk/ykrt/src/compile/jitc_yk/codegen/x64/mod.rs:164:9
  13: <ykrt::compile::jitc_yk::JITCYk as ykrt::compile::Compiler>::compile
             at /vol/extra/ltratt/yk/ykrt/src/compile/jitc_yk/mod.rs:152:18
  14: ykrt::mt::MT::queue_compile_job::{{closure}}
             at /vol/extra/ltratt/yk/ykrt/src/mt.rs:282:19
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/ops/function.rs:250:5
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/alloc/src/boxed.rs:2454:9
  17: lock_api::mutex::MutexGuard<R,T>::unlocked
             at /home/ltratt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lock_api-0.4.12/src/mutex.rs:581:9
  18: ykrt::mt::MT::queue_job::{{closure}}
             at /vol/extra/ltratt/yk/ykrt/src/mt.rs:243:29
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/codegen/x64/lsregalloc.rs:662:22:
called `Option::unwrap()` on a `None` value
```

but looking at the IR, I *think* this might be fingering the wrong culprit. I am going to investigate, but I think it's possible that trace_builder is handling over subtly wrong IR to the x64 backend.

One more thing: in the non-serialised case, we're also creating an additional trace too:

```
$ YK_LOG=4 YKD_SERIALISE_COMPILATION=1 src/lua permute.lua 2>&1 | grep "start.*tracing" | wc -l
6
$ YK_LOG=4 src/lua permute.lua 2>&1 | grep "start.*tracing" | wc -l
7
```

This might not be a smoking gun, because some traces fail to compile with:

```
yk-warning: trace-compilation-aborted: dlsym("llvm.lifetime.start.p0") returned NULL
```

and it seems we're creating 3 traces that fail in this way with serialised compilation and 4 with non-serialised compilation. I don't know why we're getting this particular name lookup problem, though.

**Comment by ltratt** [comment]
OK, it looks like this *might* be https://github.com/ykjit/yk/issues/1440 in disguise. If I apply this diff:

```diff
diff --git ykrt/src/compile/jitc_yk/codegen/x64/mod.rs ykrt/src/compile/jitc_yk/codegen/x64/mod.rs
index 04dcb255..aa296d38 100644
--- ykrt/src/compile/jitc_yk/codegen/x64/mod.rs
+++ ykrt/src/compile/jitc_yk/codegen/x64/mod.rs
@@ -2360,6 +2360,8 @@ impl CompiledTrace for X64CompiledTrace {
                 .unwrap(),
             _ => panic!("Unexpected HotLocationKind"),
         };
+        drop(hl);
+        println!("{:p}", Arc::as_ptr(&root_ctr));
 
         // Calculate the address inside the root trace we want side-traces to jump to. Currently
         //
```

and run the serialised/non-serialised cases:

```
$ YKD_SERIALISE_COMPILATION=1 src/lua permute.lua
0x7f7bb93ad230
0x7f7bb9318aa0
0x7f7bb939d700
$ src/lua permute.lua
0x7f67e13ad180
0x7f67e13ad180
0x7f67e13ad180
0x7f67e13ad180
thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/codegen/x64/lsregalloc.rs:662:22:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/codegen/x64/lsregalloc.rs:662:22:
called `Option::unwrap()` on a `None` value
0x7f67d0104770
0x7f67d0104770
0x7f67d0104770
0x7f67d0104770
thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/codegen/x64/lsregalloc.rs:662:22:
called `Option::unwrap()` on a `None` value
thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/codegen/x64/lsregalloc.rs:662:22:
called `Option::unwrap()` on a `None` value
fatal runtime error: failed to initiate panic, error 5
zsh: IOT instruction  src/lua permute.lua
```

we can see that the serialised case is identifying *three* root traces but the non-serialised case is identifying *two* root traces. That suggests that we're actually picking up the wrong root trace in side-tracing in the non-serialised case, which would give some credence to my vague feeling that we're then creating wrong IR.

**Comment by ptersilie** [comment]
Right. We should wait and see if getting rid of `set_running_trace` will fix this.

**Comment by ltratt** [comment]
Fixed by https://github.com/ykjit/yk/pull/1461.
