### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#547]
Using ykcbf I can reliably cause a segfault by:

```
$ echo 123456 | ./bf_simple_yk lang_tests/numwarp.bf
```

Here's a `gdb` backtrace:

```
core::ptr::read<u8> (src=0x1002390ab)
    at /rustc/879aff385a5fe0af78f3d45fd2f0b8762934e41e/library/core/src/ptr/mod.rs:1096
1096    /rustc/879aff385a5fe0af78f3d45fd2f0b8762934e41e/library/core/src/ptr/mod.rs: No such file or directory.
(gdb) bt
#0  core::ptr::read<u8> (src=0x1002390ab)
    at /rustc/879aff385a5fe0af78f3d45fd2f0b8762934e41e/library/core/src/ptr/mod.rs:1096
#1  0x00007ffff52dad8f in yksgi::SGInterp::load (self=0x7fffffffd918)
    at yksgi/src/lib.rs:445
#2  0x00007ffff52d9107 in yksgi::SGInterp::interpret (self=0x7fffffffd918)
    at yksgi/src/lib.rs:223
#3  0x00007ffff52c1fd7 in ykcapi::yk_stopgap (sm_addr=0x7ffff4ac2000, 
    sm_size=488, aotmap=0x7fffffffdc50, actframes=0x7fffffffe060, 
    retaddr=140737298282887, rsp=0x7fffffffdc08) at ykcapi/src/lib.rs:236
#4  0x00007ffff52c27e9 in ykcapi::__llvm_deoptimize (addr=<optimized out>, 
    size=<optimized out>, aotmap=<optimized out>, curpos=<optimized out>)
    at ykcapi/src/lib.rs:259
#5  0x0000000000001000 in ?? ()
#6  0x00007ffff52c27d0 in ?? ()
   from /home/ltratt/yk/target/debug/deps/libykcapi.so
#7  0x00007fffffffdc50 in ?? ()
#8  0x00007fffffffe060 in ?? ()
#9  0x00007fffffffe5f8 in ?? ()
#10 0x00000000000001e8 in ?? ()
#11 0x00007ffff4ac2000 in ?? ()
#12 0x00007fffffffe260 in ?? ()
#13 0x00007fffffffdc48 in ?? ()
#14 0x00007ffff4abb987 in __yk_compiled_trace_4 ()
#15 0x00007ffff57f707d in yktrace::CompiledTrace::real_exec (self=0x7fffe8006740, ctrlp_vars=0x7fffffffe558) at yktrace/src/lib.rs:277
#16 0x00007ffff57f6f90 in yktrace::CompiledTrace::exec (self=<optimized out>, ctrlp_vars=<optimized out>) at yktrace/src/lib.rs:246
#17 0x0000000000000000 in ?? ()
```

**Comment by ltratt** [comment]
[I just updated the backtrace to a more recent yksgi -- mea culpa!]
