### ISSUE TITLE
Bug in compressed return logic?

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#874]
On [one occasion](https://github.com/ykjit/yk/pull/870#issuecomment-1758293195) we saw:

```
19:44:38 ---- lang_tests::unroll_safe_implies_noinline.c stderr ----
19:44:38 
19:44:38 Pattern (error at line 2):
19:44:38    |...
19:44:38 >> |--- Begin aot ---
19:44:38    |...
19:44:38    |call void @never_aot_inline(i32 noundef ...
19:44:38    |...
19:44:38    ...
19:44:38 
19:44:38 Text (error at line 4):
19:44:38    |thread '<unnamed>' panicked at hwtracer/src/pt/ykpt/mod.rs:453:13:
19:44:38    |assertion failed: taken
19:44:38    |note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
19:44:38 >> |fatal runtime error: failed to initiate panic, error 5
19:44:38 
19:44:38 ---- lang_tests::unroll_safe_implies_noinline.c stdout ----
```

Suggest we expected a compressed return, but the chip did not?

**Comment by ltratt** [comment]
I've now seen this happen in the `call_args` test:

```
---- lang_tests::call_args.c stderr ----                                        
                                                                                
Pattern (error at line 4):                                                      
   |jit-state: start-tracing                                                    
   |3: 5                                                                        
   |jit-state: stop-tracing                                                     
>> |--- Begin jit-pre-opt ---                                                   
   |...                                                                         
   |%{{res}} = add nsw i32...                                                   
   |...                                                                         
   ...                                                                          
                                                                                
Text (error at line 4):
   |jit-state: start-tracing
   |3: 5
   |jit-state: stop-tracing
>> |thread '<unnamed>' panicked at hwtracer/src/pt/ykpt/mod.rs:449:13:
   |assertion failed: taken
   |stack backtrace: 
   |   0:     0x7f4aaf593a8c - std::backtrace_rs::backtrace::libunwind::trace::h
9181ffa9c3d4a750
   ...
```

So there is definitely something going on here. [I was doing a long-running `try_repeat` for something else, which is why I stumbled on this.]

**Comment by vext01** [comment]
This was erroneously closed.

**Comment by vext01** [comment]
For the benefit of future me, Just wanted to link a relevant conversation I had with Markus:

https://github.com/intel/libipt/issues/104

**Comment by vext01** [comment]
This was erroneously closed.

**Comment by vext01** [comment]
Oddly enough, the assertion failure mentioned above has been seen in the wild when compressed returns are *disabled*!
https://github.com/ykjit/yk/pull/954#issuecomment-1926892063

I wonder if the bug is elsewhere, but only manifests sometimes when we are looking at a later TNT packet...
